name = "JackPolynomials"
uuid = "ddfd1fc9-90b3-4604-ab0e-bc3dcbfcf898"
authors = ["Stéphane Laurent <laurent_step@outlook.fr>"]
version = "1.0.0"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"

[compat]
AbstractAlgebra = "0.27.0"
DynamicPolynomials = "0.4.5"
julia = "1.6"
